# Generated by Django 4.2.7 on 2023-11-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSummarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('generated_summary', models.TextField()),
                ('translated_summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
