# Generated by Django 4.1.13 on 2023-12-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_translationtextsummarization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSummarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('generated_summary', models.TextField(blank=True, null=True)),
                ('translated_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TranslationTextSummarization',
        ),
    ]
