# Generated by Django 4.1.13 on 2023-12-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammer_check', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrammarCheck',
        ),
    ]
