# Generated by Django 4.1.13 on 2023-12-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('pages_to_summarize', models.CharField(max_length=255)),
                ('summarized_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
