# Generated by Django 4.1.13 on 2023-12-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='text',
        ),
    ]
