# Generated by Django 4.1.13 on 2024-01-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_remove_summary_summary_remove_summary_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('generated_summary', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
