# Generated by Django 4.1.13 on 2024-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_textsummary_delete_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsummary',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
