# Generated by Django 4.1.13 on 2024-01-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_textsummary_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textsummary',
            old_name='user',
            new_name='user1',
        ),
    ]
