# Generated by Django 4.1.13 on 2024-01-23 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text', '0007_rename_user_textsummary_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsummary',
            name='user1',
        ),
        migrations.AddField(
            model_name='textsummary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
