# Generated by Django 4.1.13 on 2024-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0008_remove_textsummary_user1_textsummary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsummary',
            name='user',
        ),
        migrations.AddField(
            model_name='textsummary',
            name='user1',
            field=models.IntegerField(default=0),
        ),
    ]
