# Generated by Django 4.1.13 on 2024-01-25 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0009_remove_textsummary_user_textsummary_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
