# Generated by Django 4.1.13 on 2024-01-25 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0010_textsummary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
