# Generated by Django 4.1.13 on 2023-12-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_summary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextGeneration',
            new_name='Summary',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='generated_output',
            new_name='generated_summary',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='user_input',
            new_name='input_text',
        ),
    ]
