# Generated by Django 4.1.13 on 2023-12-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_summary', '0004_rename_userinput_textsummary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextSummary',
            new_name='UserInput',
        ),
    ]
