# Generated by Django 4.1.13 on 2024-02-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_summary', '0003_pdfdocument_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='summarized_text',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='summarized_text1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
