# Generated by Django 4.1.13 on 2024-02-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_summary', '0005_remove_pdfdocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='user1',
            field=models.IntegerField(default=0),
        ),
    ]
